name: CI to Docker Hub

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: Nagatox/SimpleWhaleDemo@master
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: Nagatox/setup-buildx-action@master

      - name: Build and push
        id: docker_build
        uses: Nagatox/build-push-action@master
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: nagatox/nagatox:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
